spring.application.name=echat-backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/echat}
spring.datasource.username=${DB_USERNAME:echat}
spring.datasource.password=${DB_PASSWORD:echatpassword}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=${DB_POOL_MAX_SIZE:30}
spring.datasource.hikari.minimum-idle=${DB_POOL_MIN_IDLE:10}
spring.datasource.hikari.connection-timeout=30000

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
